* ArtsHack TileMill Session Notes
This repo includes the "lesson plan" (in the loosest sense) and slides for the "Intro to Programming, Geodata, and TileMill" session presented at University of Melbourne on June 4th 2013.
* Slides
The presentation itself can be accessed through Github Pages here: http://mechamoth.github.io/artshack/
I'm not certain that I've got it set up properly to automatically update that page if I update the main content, so that might take some fiddling to get working. In the short term, you can just download the zip archive of this repo, and open the "index.html" file in the "presentation" folder on your local computer.
* Author
All content (c) Thom Mackey, 2013. Originally produced for the University of Melbourne.
Presentation uses reveal.js, an MIT-licensed JavaScript library by Hakim El Hattab.
* License
Content in this repo is licensed [[http://creativecommons.org/licenses/by/3.0/au/deed.en_GB][Creative Commons Attribution 3.0 Australia License]] (CC BY 3.0 AU). That means you can take it, copy it, change it, and sell it, as long as you give the original author credit.
